/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practicaldlc;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author laura.tascon
 */
public class Menu extends javax.swing.JFrame {
    public static LDLC lista = new LDLC();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotonEsVacia = new javax.swing.JButton();
        BotonPrimerNodo = new javax.swing.JButton();
        BotonUltimoNodo = new javax.swing.JButton();
        BotonMostrar = new javax.swing.JButton();
        BotonAnterior = new javax.swing.JButton();
        BotonActualizar = new javax.swing.JButton();
        BotonBuscar = new javax.swing.JButton();
        BotonBorrar = new javax.swing.JButton();
        BotonOrdenar = new javax.swing.JButton();
        BotonIntercambiar = new javax.swing.JButton();
        Botoneliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        BotonEsVacia.setText("Es vacia");
        BotonEsVacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEsVaciaActionPerformed(evt);
            }
        });

        BotonPrimerNodo.setText("Primer nodo");
        BotonPrimerNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPrimerNodoActionPerformed(evt);
            }
        });

        BotonUltimoNodo.setText("Ultimo Nodo");
        BotonUltimoNodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonUltimoNodoActionPerformed(evt);
            }
        });

        BotonMostrar.setText("Mostrar lista");
        BotonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMostrarActionPerformed(evt);
            }
        });

        BotonAnterior.setText("Anterior");
        BotonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAnteriorActionPerformed(evt);
            }
        });

        BotonActualizar.setText("Actualizar lista (insertar nodo)");
        BotonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonActualizarActionPerformed(evt);
            }
        });

        BotonBuscar.setText("Buscar dato");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        BotonBorrar.setText("Borrar");
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });

        BotonOrdenar.setText("Ordenar desendientemente");
        BotonOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOrdenarActionPerformed(evt);
            }
        });

        BotonIntercambiar.setText("Intercambiar consecutivos");
        BotonIntercambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIntercambiarActionPerformed(evt);
            }
        });

        Botoneliminar.setText("Eliminar lista");
        Botoneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotoneliminarActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista Doblemente Ligada Circular");

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Botoneliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonIntercambiar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonOrdenar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBorrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonBuscar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonActualizar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                    .addComponent(BotonAnterior, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonUltimoNodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonEsVacia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonMostrar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotonPrimerNodo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(salir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonEsVacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonUltimoNodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonPrimerNodo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonMostrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonAnterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonOrdenar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonIntercambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Botoneliminar)
                .addGap(18, 18, 18)
                .addComponent(salir)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEsVaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEsVaciaActionPerformed
        
        if(lista.esVacia()){
          JOptionPane.showMessageDialog(null, "La lista se encuentra vacía: ");  
        }else{
        JOptionPane.showMessageDialog(null, "La lista tiene datos " );
        }
    }//GEN-LAST:event_BotonEsVaciaActionPerformed

    private void BotonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonActualizarActionPerformed
        Insertar insertar = new Insertar();
        insertar.setVisible(true);
        dispose();
    }//GEN-LAST:event_BotonActualizarActionPerformed

    private void BotonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMostrarActionPerformed
        lista.mostrarLista();
    }//GEN-LAST:event_BotonMostrarActionPerformed

    private void BotonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAnteriorActionPerformed
        if(lista.esVacia()){
            JOptionPane.showMessageDialog(null, "No es posible \nLa lista se encuentra vacía " );
        }else{
        try{
        String dato;
        dato= JOptionPane.showInputDialog(null, "Ingrese un dato:", "Anterior de", JOptionPane.QUESTION_MESSAGE);
        lista.anterior(Integer.parseInt(dato));
        }catch (NumberFormatException e) {
               JOptionPane.showMessageDialog(null,"Debe ingresar un numero");
            }
        
        }
    }//GEN-LAST:event_BotonAnteriorActionPerformed

    private void BotonUltimoNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonUltimoNodoActionPerformed
        NodoDoble ultimo;
        if(lista.esVacia()){
             JOptionPane.showMessageDialog(null, "No es posible \nLa lista se encuentra vacía " );
        }else{
            ultimo = lista.ultimoNodo();          
            int dato= ultimo.retornaDato();
            JOptionPane.showMessageDialog(null, "El ultimo dato es: " + dato);
        }
    }//GEN-LAST:event_BotonUltimoNodoActionPerformed

    private void BotonPrimerNodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPrimerNodoActionPerformed
        boolean vacio = lista.esVacia();
        if(lista.esVacia()){
            JOptionPane.showMessageDialog(null, "No es posible \nLa lista se encuentra vacía " );
        }else{
            NodoDoble primero = lista.primerNodo();
            int dato= primero.retornaDato();
            JOptionPane.showMessageDialog(null, "El primer dato es: " + dato);
        }
    }//GEN-LAST:event_BotonPrimerNodoActionPerformed

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
    
    try{
        String d;
        d= JOptionPane.showInputDialog(null, "Ingrese un dato:", "Buscar dato", JOptionPane.QUESTION_MESSAGE);
        NodoDoble dato = lista.buscarDato(Integer.parseInt(d));
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Debe ingresar un numero");
    } 
            
    }//GEN-LAST:event_BotonBuscarActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
       
    try{
        String d;
        d= JOptionPane.showInputDialog(null, "Ingrese un dato:", "Borrar dato", JOptionPane.QUESTION_MESSAGE);
        NodoDoble dato = lista.buscarDato(Integer.parseInt(d));
        if(dato != null){
        lista.borrar(dato);
        }
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null,"Debe ingresar un numero");
    } 
    }//GEN-LAST:event_BotonBorrarActionPerformed

    private void BotoneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotoneliminarActionPerformed
        lista.eliminarLista();
    }//GEN-LAST:event_BotoneliminarActionPerformed

    private void BotonIntercambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIntercambiarActionPerformed
        lista.intercambiarConsecutivos();
    }//GEN-LAST:event_BotonIntercambiarActionPerformed

    private void BotonOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOrdenarActionPerformed
       lista.ordenarDescendentemente();
    }//GEN-LAST:event_BotonOrdenarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        JOptionPane.showMessageDialog(null,"profe, te queremos, *corazoncito*");
        dispose();
    }//GEN-LAST:event_salirActionPerformed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonActualizar;
    private javax.swing.JButton BotonAnterior;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonEsVacia;
    private javax.swing.JButton BotonIntercambiar;
    private javax.swing.JButton BotonMostrar;
    private javax.swing.JButton BotonOrdenar;
    private javax.swing.JButton BotonPrimerNodo;
    private javax.swing.JButton BotonUltimoNodo;
    private javax.swing.JButton Botoneliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
